import Head from 'next/head'
import React from 'react'
import Navbar from '../Navbar'
import Footer from '../Footer'

function Page({children,style}) {
    
  return (
    <>
      <Head>
        <title>Stork Event</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://res.cloudinary.com/droheqpxn/image/upload/v1655606264/etstur/logo_g04c5g.png" />
      </Head>
      <Navbar style={style}/>
      {children}
      <Footer/>
    </>
  )
}

export default Page