import Head from 'next/head'
import React from 'react'
import Navbar from '../Navbar'
import Footer from '../Footer'

function Page({children}) {
    
  return (
    <>
        <Head>
          <title>Event</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="https://res.cloudinary.com/droheqpxn/image/upload/v1646281827/hefore/hefore_1_pjkipc.png" />
        </Head>
        <Navbar/>
        {children}
        <Footer/>
    </>
  )
}

export default Page